language: R
warnings_are_errors: true
cache: packages

matrix:
    include:
        - r: release
          env: DEPS=cran
          dist: trusty # 14.04
          env: R_CODECOV=true
        - r: release
          env: DEPS=cran
          os: osx
        - r: oldrel
          env: DEPS=cran
          dist: trusty # 14.04
        - r: oldrel
          env: DEPS=cran
          os: osx
          #- r: devel
          #env: DEPS=cran
          #os: linux
          #- r: devel
          #env: DEPS=cran
          #os: osx

addons:
    apt:
        packages:
            - libpoppler-cpp-dev
            - libgsl0-dev 

#before_install:
#    - sudo apt install --yes libgsl0-dev libpoppler-cpp-dev
#      #- Rscript -e 'install.packages("topicmodels"))'

notifications:
  email:
    on_success: change
    on_failure: change

# Prevents Travis timeout for building libpoppler
before_install:
    - (while true; do echo 'Ping? Pong!'; sleep 500; done) &

r_github_packages:
      - jimhester/covr

after_success:
    - Rscript -e "covr::codecov()"
